server:
  port: 8082

spring:
  application:
    name: order-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/donatech
    username: donatech
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /order/v3/api-docs
    config-url: /order/v3/api-docs
    urls:
      - name: Order API
        url: /order/v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      users-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
      catalog-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      users-service:
        timeoutDuration: 3s
      catalog-service:
        timeoutDuration: 3s
