server:
  port: 8087

spring:
  application:
    name: shipping-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/donatech}
    username: ${POSTGRES_USER:donatech}
    password: ${POSTGRES_PASSWORD:wordpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
