server:
  port: 8084

spring:
  application:
    name: auth-service

donatech:
  app:
    jwtSecret: ${JWT_SECRET:donatechSecretKey12345678901234567890123456789012}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /auth/v3/api-docs
    config-url: /auth/v3/api-docs
    urls:
      - name: Auth API
        url: /auth/v3/api-docs
