management:
  endpoints:
    web:
      exposure:
        include: health,info

routing:
  osrm-base-url: http://router.project-osrm.org
  nominatim-base-url: https://nominatim.openstreetmap.org

resilience4j:
  circuitbreaker:
    instances:
      routingService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

logging:
  level:
    com.donatech: INFO

server:
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false