server:
  port: 8081

spring:
  application:
    name: catalog-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  datasource:
    url: jdbc:postgresql://localhost:5432/donatech
    username: catalog_user
    password: ${CATALOG_DB_PASS:catalog_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET search_path TO catalog"
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: catalog
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /catalog/v3/api-docs
    config-url: /catalog/v3/api-docs/swagger-config
    urls:
      - name: Catalog API
        url: /catalog/v3/api-docs
