spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.donatech: INFO
    org.springframework.amqp: WARN

server:
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html