-- ============================================================
-- SEED DATA: supports-service (schema: supports)
-- Sin seeds: los tickets de soporte se crean por usuarios reales
-- o automáticamente vía eventos (validación de campañas/transferencias).
-- ============================================================
